spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa: # spring ??? ????? ???????.
    hibernate:
      ddl-auto: create    # ddl-auto: update? ?? ??? ??? h2??????? ?????? ?? ? ??. ??? ??? ??.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true